services:
  - type: web
    name: payswap-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: worker
    name: payswap-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py